# Copyright (C) 2023 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

name: ORT Docker Image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.versions'
      - 'Dockerfile'
      - '.github/workflows/docker-ort.yml'
  push:
    branches:
      - 'main'
    tags:
      - '*'

env:
  REGISTRY: ghcr.io

permissions: write-all

jobs:
  base_image:
    name: Base image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build base image
        uses: ./.github/actions/ortdocker
        with:
          name: base
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "${{ env.JAVA_VERSION }}-jdk-${{ env.UBUNTU_VERSION }}"
          build-args: |
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            UBUNTU_VERSION=${{ env.UBUNTU_VERSION }}

  nodejs_image:
    name: NodeJS image
    needs: [ base_image ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build NodeJS image
        uses: ./.github/actions/ortdocker
        with:
          name: nodejs
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "${{ env.NODEJS_VERSION }}"
          build-args: |
            NODEJS_VERSION=${{ env.NODEJS_VERSION }}
            NPM_VERSION=${{ env.NPM_VERSION }}
            PNPM_VERSION=${{ env.PNPM_VERSION }}
            YARN_VERSION=${{ env.YARN_VERSION }}

  golang_image:
    name: Golang image
    needs: [ base_image ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build Golang image
        uses: ./.github/actions/ortdocker
        with:
          name: golang
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "${{ env.GO_VERSION }}"
          build-args: |
            GO_DEP_VERSION=${{ env.GO_DEP_VERSION }}
            GO_VERSION=${{ env.GO_VERSION }}

  android_image:
    name: Android image
    needs: [ base_image ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build Android image
        uses: ./.github/actions/ortdocker
        with:
          name: android
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "${{ env.ANDROID_CMD_VERSION }}"
          build-args: |
            ANDROID_CMD_VERSION=${{ env.ANDROID_CMD_VERSION }}

  dart_image:
    name: Dart image
    needs: [ base_image ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build Dart image
        uses: ./.github/actions/ortdocker
        with:
          name: dart
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "${{ env.DART_VERSION }}"
          build-args: |
            DART_VERSION=${{ env.DART_VERSION }}

  swift_image:
    name: Swift image
    needs: [ base_image ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV
      - name: Build Swift image
        uses: ./.github/actions/ortdocker
        with:
          name: swift
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "${{ env.SWIFT_VERSION }}"
          build-args: |
            SWIFT_VERSION=${{ env.SWIFT_VERSION }}

  # Minimal Runtime ORT image
  # -------------------------
  minimal_image:
    needs:
      [ base_image, nodejs_image, golang_image ]
    name: Build ORT minimal image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          cat .versions >> $GITHUB_ENV

      - name: Get ORT current version
        run: |
          ORT_VERSION=$(./gradlew -q properties --property version | sed -nr "s/version: (.+)/\1/p")
          echo "ORT_VERSION=${ORT_VERSION}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: lowercase REPO_OWNER
        shell: bash
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Extract components metadata (tags, labels)
        id: meta-ort-minimal
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/ort-minimal
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=snapshot
            type=pep440,pattern={{version}}
            type=raw,value=${{ env.ORT_VERSION }}
            type=ref,event=tag

      - name: Build ORT minimal image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: minimal
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
          load: false
          build-args: |
            NODEJS_VERSION=${{ env.NODEJS_VERSION }}
            ORT_VERSION=${{ env.ORT_VERSION }}
          tags: |
            ${{ steps.meta-ort-minimal.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-contexts: |
            base=docker-image://${{ env.REGISTRY }}/${{ env.REPO }}/base:latest
            nodejs=docker-image://${{ env.REGISTRY }}/${{ env.REPO }}/nodejs:latest
            golang=docker-image://${{ env.REGISTRY }}/${{ env.REPO }}/golang:latest

  # Full Runtime ORT image
  # ----------------------
  ort_image:
    name: Build ORT image
    needs:
      [ minimal_image, android_image, dart_image, swift_image ]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get ORT current version
        run: |
          ORT_VERSION=$(./gradlew -q properties --property version | sed -nr "s/version: (.+)/\1/p")
          echo "ORT_VERSION=${ORT_VERSION}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker build
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: downcase REPO_OWNER
        shell: bash
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Extract components metadata (tags, labels)
        id: meta-ort
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/ort
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern=snapshot
            type=pep440,pattern={{version}}
            type=raw,value=${{ env.ORT_VERSION }}
            type=ref,event=tag

      - name: Build ORT image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: run
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
          load: false
          tags: |
            ${{ steps.meta-ort.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-contexts: |
            minimal=docker-image://${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/ort-minimal:${{ env.ORT_VERSION }}
            android=docker-image://${{ env.REGISTRY }}/${{ env.REPO }}/android:latest
            swift=docker-image://${{ env.REGISTRY }}/${{ env.REPO }}/swift:latest
            dart=docker-image://${{ env.REGISTRY }}/${{ env.REPO }}/dart:latest