name: Wrapper Validation

on:
  workflow_dispatch:

jobs:
  gradle-wrapper:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Validate Wrapper
      uses: gradle/wrapper-validation-action@v2
